#define INDIRECT_VALUE_TWEAK_VALUE 42

// Configuration macros:

// Configurable extension (w.r.t. p1950r2):
// nsiv_CONFIG_NO_EXTENSIONS
// nsiv_CONFIG_NO_EXTENSION_REF_QUALIFIED_OPERATORS
// nsiv_CONFIG_NO_EXTENSION_VALUE_MEMBERS
// nsiv_CONFIG_NO_EXTENSION_GET_CPY_DEL_MEMBERS
// nsiv_CONFIG_NO_EXTENSION_RELATIONAL_OPERATORS
// nsiv_CONFIG_NO_EXTENSION_STD_HASH
