#define INDIRECT_VALUE_TWEAK_VALUE 42

// Configuration macros
// nsiv_CONFIG_NO_EXTENSIONS
// nsiv_CONFIG_NO_EXTENSION_REF_QUALIFIED_OPERATORS
// nsiv_CONFIG_NO_EXTENSION_VALUE_MEMBERS
// nsiv_CONFIG_NO_EXTENSION_RELATIONAL_OPERATORS
// nsiv_CONFIG_NO_EXTENSION_STD_HASH
